version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9990:9090
    volumes:
      - ./build/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    #command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  grafana:
    build:
      context: ./build/grafana
    volumes:
      - /home/maborak/build/grafana-dashboards/dashboards:/etc/grafana/mysql_dashboards
    ports:
     - "3000:3000"
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${GC_SMTP_HOST:-localhost}
      - GF_SMTP_USER=${GC_SMTP_USER:-localhost}
      - GF_SMTP_PASSWORD=${GC_SMTP_PASSWORD:-localhost}
      - GF_SMTP_FROM_ADDRESS=${GC_SMTP_FROM_ADDRESS:-localhost}
      - GF_SMTP_FROM_NAME=${GC_SMTP_FROM_NAME:-localhost}
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

volumes:
  prometheus-data:
  grafana-data:
